### ISSUE TITLE
Not working in Laravel 9

### ISSUE THREAD

**Issue by gboquizosanchez** [C0deWiser/polyglot#2]
exception: "Symfony\\Component\\Finder\\Exception\\DirectoryNotFoundException"
file: "/var/www/html/vendor/symfony/finder/Finder.php"
line: 590
message: "The \"/var/www/html/resources/lang\" directory does not exist."

Laravel has changed lang directory to a superior level, so I think the finder don't find files and 500 error appear.

**Comment by Cellard** [comment]
Fixed

**Comment by gboquizosanchez** [comment]
Thanks!
